-- 로컬 개발용 샘플 데이터. db/migration이 아니라 db/dev-migration에 있어서 prod 프로파일(application-prod.yml)
-- 에서는 flyway.locations에 포함되지 않아 적용되지 않는다.
--
-- 모든 PK는 GENERATED BY DEFAULT AS IDENTITY라 값을 직접 지정해서 넣을 수 있다 (ALWAYS였다면
-- OVERRIDING SYSTEM VALUE가 필요했을 것). 대신 시퀀스를 안 건드리기 때문에, 파일 끝에서
-- setval로 시퀀스를 맞춰주지 않으면 다음 앱 기동 후 INSERT에서 PK 충돌이 난다.

-- ── member ──────────────────────────────────────────────
INSERT INTO users (user_id, email, password_hash, name, phone, role, status) VALUES
    (1, 'kim@example.com', '$2a$10$dummydummydummydummydu', '김철수', '010-1111-2222', 'USER', 'ACTIVE'),
    (2, 'admin@example.com', '$2a$10$dummydummydummydummydu', '운영자', '010-2222-3333', 'ADMIN', 'ACTIVE');

INSERT INTO guests (guest_id, expires_at) VALUES
    ('11111111-1111-1111-1111-111111111111', now() + interval '7 days');

INSERT INTO social_accounts (social_account_id, user_id, provider, provider_user_id, email) VALUES
    (1, 1, 'KAKAO', 'kakao_1000', 'kim@example.com');

-- ── store ───────────────────────────────────────────────
INSERT INTO store_service_types (service_type_id, code, name) VALUES
    (1, 'NEW_LINE', '신규가입'),
    (2, 'PORT_IN', '번호이동'),
    (3, 'NAME_CHANGE', '명의변경'),
    (4, 'USIM_REISSUE', '유심재발급');

INSERT INTO stores (store_id, name, phone, address, region_code, latitude, longitude, status) VALUES
    (1, '텔미 강남점', '02-1234-5678', '서울특별시 강남구 테헤란로 123', 'SEOUL', 37.498095, 127.027610, 'OPEN'),
    (2, '텔미 부산점', '051-1234-5678', '부산광역시 해운대구 센텀중앙로 45', 'BUSAN', 35.169100, 129.130600, 'OPEN');

INSERT INTO store_services (store_id, service_type_id) VALUES
    (1, 1), (1, 2), (1, 4),
    (2, 1), (2, 4);

INSERT INTO store_hours (store_id, day_of_week, open_time, close_time, is_closed) VALUES
    (1, 0, NULL, NULL, true),
    (1, 1, '10:00', '19:00', false),
    (1, 2, '10:00', '19:00', false),
    (1, 3, '10:00', '19:00', false),
    (1, 4, '10:00', '19:00', false),
    (1, 5, '10:00', '19:00', false),
    (1, 6, '10:00', '17:00', false),
    (2, 0, NULL, NULL, true),
    (2, 1, '10:00', '20:00', false),
    (2, 2, '10:00', '20:00', false),
    (2, 3, '10:00', '20:00', false),
    (2, 4, '10:00', '20:00', false),
    (2, 5, '10:00', '20:00', false),
    (2, 6, '10:00', '18:00', false);

-- ── faq (embedding은 실제 임베딩 파이프라인 없이 더미 1024차원 벡터로 채운다) ──
INSERT INTO faqs (faq_id, category, question, answer, policy_ref, version, status, created_by, updated_by) VALUES
    (1, 'BILLING', '요금제는 언제 변경할 수 있나요?', '요금제는 매월 1회, 영업일 기준 변경 신청일로부터 다음날 자정에 적용됩니다.', 'POLICY-001', 1, 'ACTIVE', 2, 2),
    (2, 'USIM', '유심 재발급은 어떻게 하나요?', '가까운 매장을 방문해 신분증을 지참하시면 즉시 재발급이 가능합니다.', 'POLICY-014', 1, 'ACTIVE', 2, 2);

-- 모든 성분이 같은 값인 벡터(array_fill)는 서로 평행해서 코사인 유사도가 항상 1.0으로 나와
-- 유사도 랭킹을 구분할 수 없다. 성분마다 값이 달라지는 패턴으로 채워 방향이 달라지게 한다.
INSERT INTO faq_embeddings (faq_id, embedding, faq_version) VALUES
    (1, (SELECT ('[' || string_agg((0.001 + 0.0004 * (n % 13))::text, ',' ORDER BY n) || ']')::vector FROM generate_series(1, 1024) AS n), 1),
    (2, (SELECT ('[' || string_agg((0.002 + 0.0004 * (n % 17))::text, ',' ORDER BY n) || ']')::vector FROM generate_series(1, 1024) AS n), 1);

-- ── chat (session 1은 회원, session 2는 게스트 — ck_session_owner 양쪽 분기를 모두 보여준다) ──
INSERT INTO chat_sessions (session_id, user_id, guest_id, title, status, summary) VALUES
    (1, 1, NULL, '요금제 문의', 'ACTIVE', NULL),
    (2, NULL, '11111111-1111-1111-1111-111111111111', '유심 재발급 문의', 'CLOSED', '부산점 방문 안내로 종료');

INSERT INTO chat_messages (message_id, session_id, sequence_no, reply_to_id, role, message_type, content, status, answer_basis, follow_ups, store_results) VALUES
    (1, 1, 1, NULL, 'USER', 'QUESTION', '요금제 변경하고 싶어요', 'COMPLETED', NULL, NULL, NULL),
    (2, 1, 2, 1, 'ASSISTANT', 'ANSWER', '요금제는 매월 1회 변경 가능하며 신청 다음날 자정에 적용됩니다.', 'COMPLETED', 'GROUNDED', '["변경 방법도 알려줘"]'::jsonb, NULL),
    (3, 2, 1, NULL, 'USER', 'QUESTION', '유심 재발급 어디서 하나요?', 'COMPLETED', NULL, NULL, NULL),
    (4, 2, 2, 3, 'ASSISTANT', 'STORE_RESULT', '근처 매장을 안내해드릴게요.', 'COMPLETED', 'GROUNDED', NULL, '[{"storeId":2,"name":"텔미 부산점"}]'::jsonb);

INSERT INTO consult_requests (consult_request_id, session_id, origin_message_id, subquery_order, intent, query_text, status, version) VALUES
    (1, 1, 1, 1, 'FAQ', '요금제 변경하고 싶어요', 'DONE', 1),
    (2, 2, 3, 1, 'STORE', '유심 재발급 어디서 하나요?', 'DONE', 1);

INSERT INTO consult_conditions (condition_id, consult_request_id, condition_key, condition_value, source, status) VALUES
    (1, 2, 'region', 'BUSAN', 'EXTRACTED', 'FILLED');

INSERT INTO query_routings (routing_id, message_id, intent, refined_query, extracted_conditions, confidence, method) VALUES
    (1, 1, 'FAQ', '요금제 변경 방법', NULL, 0.950, 'LLM'),
    (2, 3, 'STORE', '유심 재발급 매장 안내', '{"region":"BUSAN"}'::jsonb, 0.880, 'LLM');

INSERT INTO chat_executions (execution_id, session_id, input_message_id, output_message_id, status, ended_at) VALUES
    (1, 1, 1, 2, 'COMPLETED', now()),
    (2, 2, 3, 4, 'COMPLETED', now());

INSERT INTO llm_generations (generation_id, execution_id, task_type, attempt, model, prompt_version, context_count, first_token_ms, total_ms, status) VALUES
    (1, 1, 'RAG_ANSWER', 1, 'gpt-4o-mini', 'v1', 2, 320, 980, 'SUCCESS'),
    (2, 2, 'RAG_ANSWER', 1, 'gpt-4o-mini', 'v1', 1, 280, 850, 'SUCCESS');

-- 회원 피드백 1건 + 게스트 피드백 1건 (uk_feedback_user/uk_feedback_guest 부분 유니크 인덱스 대상 컬럼을 각각 채운다)
INSERT INTO message_feedback (feedback_id, message_id, user_id, guest_id, rating, reason_code, comment) VALUES
    (1, 2, 1, NULL, 'LIKE', NULL, NULL),
    (2, 4, NULL, '11111111-1111-1111-1111-111111111111', 'DISLIKE', 'HARD_TO_READ', '매장 리스트가 잘 안 보여요');

INSERT INTO message_sources (source_id, message_id, faq_id, title_snapshot, faq_version, faq_updated_at, search_rank, score) VALUES
    (1, 2, 1, '요금제는 언제 변경할 수 있나요?', 1, CURRENT_DATE, 1, 0.9231);

-- ── identity 시퀀스를 방금 넣은 최대값 다음으로 맞춘다 ──
-- (GENERATED BY DEFAULT AS IDENTITY 컬럼에 값을 직접 넣으면 시퀀스는 자동으로 따라가지 않는다.
--  이 작업을 빼먹으면 다음 앱 기동 후 첫 INSERT에서 "duplicate key" 에러가 난다.)
SELECT setval(pg_get_serial_sequence('users', 'user_id'), (SELECT MAX(user_id) FROM users));
SELECT setval(pg_get_serial_sequence('social_accounts', 'social_account_id'), (SELECT MAX(social_account_id) FROM social_accounts));
SELECT setval(pg_get_serial_sequence('store_service_types', 'service_type_id'), (SELECT MAX(service_type_id) FROM store_service_types));
SELECT setval(pg_get_serial_sequence('stores', 'store_id'), (SELECT MAX(store_id) FROM stores));
SELECT setval(pg_get_serial_sequence('faqs', 'faq_id'), (SELECT MAX(faq_id) FROM faqs));
SELECT setval(pg_get_serial_sequence('chat_sessions', 'session_id'), (SELECT MAX(session_id) FROM chat_sessions));
SELECT setval(pg_get_serial_sequence('chat_messages', 'message_id'), (SELECT MAX(message_id) FROM chat_messages));
SELECT setval(pg_get_serial_sequence('consult_requests', 'consult_request_id'), (SELECT MAX(consult_request_id) FROM consult_requests));
SELECT setval(pg_get_serial_sequence('consult_conditions', 'condition_id'), (SELECT MAX(condition_id) FROM consult_conditions));
SELECT setval(pg_get_serial_sequence('query_routings', 'routing_id'), (SELECT MAX(routing_id) FROM query_routings));
SELECT setval(pg_get_serial_sequence('chat_executions', 'execution_id'), (SELECT MAX(execution_id) FROM chat_executions));
SELECT setval(pg_get_serial_sequence('llm_generations', 'generation_id'), (SELECT MAX(generation_id) FROM llm_generations));
SELECT setval(pg_get_serial_sequence('message_feedback', 'feedback_id'), (SELECT MAX(feedback_id) FROM message_feedback));
SELECT setval(pg_get_serial_sequence('message_sources', 'source_id'), (SELECT MAX(source_id) FROM message_sources));
