-- TEL-ME 초기 스키마
--
-- 머지 전에 V1~V8을 하나로 합친 파일이다. 이 시점까지 Flyway를 쓴 사람이 담당자뿐이고
-- 배포된 환경도 없어서, 8개 파일에 흩어진 "만들었다 지우는" 이력을 남길 이유가 없었다.
-- (V8이 V1~V6가 만든 인덱스·CHECK를 되돌리는 구조였다.)
--
-- 인덱스와 제약은 ERD의 "인덱스" 섹션에 있는 것 + 벡터 검색용 HNSW만 둔다.
-- 나머지는 각 기능 담당자가 실제 쿼리 모양이 나온 뒤에 추가한다. 인덱스는 어느 컬럼을
-- 어떤 순서로 걸지가 쿼리에 달려 있어서, 미리 깔면 안 쓰이는 인덱스만 남는다.
--
-- 다만 CHECK 제약은 기한이 다르다. 테이블이 비어 있을 때는 추가가 공짜지만 데이터가
-- 쌓인 뒤에는 ADD CONSTRAINT가 기존 행 검증에서 실패한다. 운영 데이터 투입 전까지는
-- 반드시 정리해야 한다. 자세한 내용은 .review/erd-issues.md 참고.

-- ─────────────────────────────────────────────────────────────────────
-- 확장
-- ─────────────────────────────────────────────────────────────────────
-- AWS RDS/Aurora PostgreSQL은 docker-entrypoint-initdb.d 같은 컨테이너 초기화 스크립트를
-- 실행하지 않으므로, 로컬/CI/RDS 모두에서 동일하게 적용되도록 Flyway가 직접 관리한다.
-- RDS/Aurora에서는 마스터 유저가 별도 권한 없이 허용 목록에 있는 확장을 생성할 수 있다.
CREATE EXTENSION IF NOT EXISTS vector;

-- ─────────────────────────────────────────────────────────────────────
-- 공통 함수
-- ─────────────────────────────────────────────────────────────────────
-- PostgreSQL은 MySQL의 "ON UPDATE CURRENT_TIMESTAMP"가 없어서 updated_at 자동 갱신은
-- 트리거로 구현한다. updated_at 컬럼을 가진 모든 테이블이 이 함수를 공유한다.
CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─────────────────────────────────────────────────────────────────────
-- 회원 · 비회원
-- ─────────────────────────────────────────────────────────────────────
-- PK는 SERIAL이 아니라 IDENTITY를 쓴다. SQL 표준이고 시퀀스 소유권이 컬럼에 묶인다.
-- BY DEFAULT라서 시드 SQL에서 값을 직접 넣을 수 있다 (ALWAYS면 OVERRIDING SYSTEM VALUE 필요).
CREATE TABLE users (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) UNIQUE,              -- 소셜 전용 회원은 NULL
    password_hash VARCHAR(255),                     -- 소셜 전용 회원은 NULL
    name          VARCHAR(50),
    phone         VARCHAR(20),
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',   -- USER / ADMIN
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE', -- ACTIVE / SUSPENDED / WITHDRAWN
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    withdrawn_at  TIMESTAMPTZ                       -- 소프트 삭제
);

CREATE TABLE guests (
    guest_id       UUID PRIMARY KEY,                -- guestId 쿠키로 발급
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at   TIMESTAMPTZ,
    expires_at     TIMESTAMPTZ NOT NULL,
    merged_user_id BIGINT REFERENCES users (user_id),  -- 승계 전 NULL
    merged_at      TIMESTAMPTZ
);

CREATE TABLE social_accounts (
    social_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    provider          VARCHAR(20)  NOT NULL,        -- KAKAO / GOOGLE
    provider_user_id  VARCHAR(100) NOT NULL,        -- 소셜 식별자. 이메일 대신 주 식별자
    email             VARCHAR(255),
    connected_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_social_provider UNIQUE (provider, provider_user_id)
);

-- ─────────────────────────────────────────────────────────────────────
-- FAQ · 검색
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE faqs (
    faq_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category     VARCHAR(30) NOT NULL,              -- 10종 카테고리 코드
    question     TEXT        NOT NULL,
    answer       TEXT        NOT NULL,
    policy_ref   VARCHAR(50),                       -- docs/POLICY.md 항목 참조
    version      INT         NOT NULL DEFAULT 1,    -- 수정 시 +1
    -- SHA-256 hex는 64자 고정이지만 CHAR가 아니라 VARCHAR를 쓴다. JPA의 String 필드는
    -- VARCHAR로 매핑되어, CHAR로 두면 ddl-auto=validate가 bpchar 불일치로 실패한다.
    content_hash VARCHAR(64),
    status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE / HIDDEN / DELETED
    created_by   BIGINT REFERENCES users (user_id),
    updated_by   BIGINT REFERENCES users (user_id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()  -- 답변에 '최종 수정일'로 노출
);

CREATE TRIGGER trg_faqs_updated_at
    BEFORE UPDATE ON faqs
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- 청킹 미도입이라 faqs와 1:1
CREATE TABLE faq_embeddings (
    faq_id      BIGINT       PRIMARY KEY REFERENCES faqs (faq_id) ON DELETE CASCADE,
    embedding   vector(1024) NOT NULL,              -- bge-m3
    model_name  VARCHAR(50)  NOT NULL DEFAULT 'bge-m3',
    faq_version INT          NOT NULL,              -- faqs.version과 비교해 정합성 확인
    sync_status VARCHAR(20)  NOT NULL DEFAULT 'SYNCED', -- PENDING / SYNCED / FAILED
    embedded_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────
-- 상담
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE chat_sessions (
    session_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT REFERENCES users (user_id),
    guest_id       UUID   REFERENCES guests (guest_id),
    title          VARCHAR(100),
    status         VARCHAR(30) NOT NULL DEFAULT 'ACTIVE', -- ACTIVE / NEED_CLARIFICATION / CLOSED
    summary        TEXT,                            -- 상담 요약. 멀티턴 Context 재사용
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_active_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- JPA로는 표현이 안 되므로 서비스 레이어에서도 생성 시점에 검증해야 한다.
    CONSTRAINT ck_session_owner CHECK (user_id IS NOT NULL OR guest_id IS NOT NULL)
);
-- 승계 시 user_id를 채우고 guest_id는 유지(추적용). 새 세션으로 복사하지 않는다.

CREATE TABLE chat_messages (
    message_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT      NOT NULL REFERENCES chat_sessions (session_id) ON DELETE CASCADE,
    sequence_no   INT         NOT NULL,             -- 세션 내 순번
    reply_to_id   BIGINT      REFERENCES chat_messages (message_id),
    role          VARCHAR(20) NOT NULL,             -- USER / ASSISTANT
    message_type  VARCHAR(30) NOT NULL,             -- QUESTION / ANSWER / CLARIFICATION / STORE_RESULT / ERROR
    content       TEXT,
    status        VARCHAR(20),                      -- GENERATING / COMPLETED / FAILED / TIMEOUT / CANCELLED
    answer_basis  VARCHAR(20),                      -- GROUNDED / NO_EVIDENCE / OUT_OF_SCOPE
    follow_ups    JSONB,                            -- 후속 질문 목록
    store_results JSONB,                            -- 추천 매장 목록
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at  TIMESTAMPTZ,
    CONSTRAINT uk_message_seq UNIQUE (session_id, sequence_no)
);

-- 사용자 메시지 1회 처리 단위. 수 초 안에 끝난다.
CREATE TABLE chat_executions (
    execution_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 공통 requestId
    session_id        BIGINT      NOT NULL REFERENCES chat_sessions (session_id) ON DELETE CASCADE,
    input_message_id  BIGINT      NOT NULL REFERENCES chat_messages (message_id),
    output_message_id BIGINT      REFERENCES chat_messages (message_id),
    status            VARCHAR(20) NOT NULL,         -- RUNNING / COMPLETED / FAILED / CANCELLED
    started_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at          TIMESTAMPTZ,
    error_code        VARCHAR(50)
);

-- ─────────────────────────────────────────────────────────────────────
-- AI 처리
-- ─────────────────────────────────────────────────────────────────────
-- sub_queries는 consult_requests 행으로 표현하므로 컬럼에서 제외
CREATE TABLE query_routings (
    routing_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id           BIGINT      NOT NULL UNIQUE REFERENCES chat_messages (message_id) ON DELETE CASCADE,
    intent               VARCHAR(20) NOT NULL,      -- FAQ / STORE / BOTH / UNKNOWN
    refined_query        TEXT,                      -- 오타·구어체 정제 결과
    extracted_conditions JSONB,                     -- 지역·국가·업무 등 추출 조건
    confidence           NUMERIC(4, 3),
    method               VARCHAR(20),               -- RULE / LLM
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 여러 턴에 걸쳐 살아있는 단위. chat_executions와 생명주기가 다르다.
CREATE TABLE consult_requests (
    consult_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         BIGINT      NOT NULL REFERENCES chat_sessions (session_id) ON DELETE CASCADE,
    origin_message_id  BIGINT      NOT NULL REFERENCES chat_messages (message_id),
    subquery_order     SMALLINT    NOT NULL,        -- 분해 순서
    intent             VARCHAR(20) NOT NULL,        -- FAQ / STORE
    query_text         TEXT        NOT NULL,        -- 분해된 개별 질문
    status             VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                                                    -- PENDING / WAITING_CONDITION / DONE / CANCELLED
    version            INT         NOT NULL DEFAULT 1, -- 상태 갱신 충돌 확인 (@Version)
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_consult_requests_updated_at
    BEFORE UPDATE ON consult_requests
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- session이 아니라 consult_request에 연결 — 복합 질문에서 어느 요청이 뭘 기다리는지 구분
CREATE TABLE consult_conditions (
    condition_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consult_request_id  BIGINT      NOT NULL REFERENCES consult_requests (consult_request_id) ON DELETE CASCADE,
    condition_key       VARCHAR(50) NOT NULL,       -- REGION / TASK_TYPE / IS_MINOR 등
    condition_value     VARCHAR(255),               -- 채워지기 전 NULL
    source              VARCHAR(20),                -- EXTRACTED / ASKED
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING / FILLED / DECLINED
    asked_message_id    BIGINT      REFERENCES chat_messages (message_id),
    answered_message_id BIGINT      REFERENCES chat_messages (message_id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_condition_key UNIQUE (consult_request_id, condition_key)
);

CREATE TRIGGER trg_consult_conditions_updated_at
    BEFORE UPDATE ON consult_conditions
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- execution_id 기준: 라우팅 호출은 답변 메시지가 생기기 전에 발생한다.
CREATE TABLE llm_generations (
    generation_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id   BIGINT      NOT NULL REFERENCES chat_executions (execution_id) ON DELETE CASCADE,
    task_type      VARCHAR(30) NOT NULL,            -- ROUTING / RAG_ANSWER / CLARIFICATION / FOLLOW_UP / SUMMARY
    attempt        SMALLINT    NOT NULL DEFAULT 1,
    model          VARCHAR(50),
    prompt_version VARCHAR(30),
    context_count  INT,                             -- Context에 넣은 FAQ 수
    first_token_ms INT,
    total_ms       INT,
    status         VARCHAR(30) NOT NULL,            -- SUCCESS / NO_EVIDENCE / TIMEOUT / CONNECTION_FAILED / MODEL_ERROR / CANCELLED
    error_message  TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 스냅샷 저장: FAQ가 수정·삭제돼도 과거 답변의 근거가 남는다.
CREATE TABLE message_sources (
    source_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id     BIGINT   NOT NULL REFERENCES chat_messages (message_id) ON DELETE CASCADE,
    faq_id         BIGINT   REFERENCES faqs (faq_id),
    title_snapshot VARCHAR(200),                    -- 답변 당시 FAQ 제목
    faq_version    INT,                             -- 답변 당시 버전
    faq_updated_at DATE,                            -- 답변 당시 최종 수정일
    search_rank    SMALLINT,                        -- rank는 예약어라 개명
    score          NUMERIC(5, 4)
);

-- ─────────────────────────────────────────────────────────────────────
-- 품질
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE message_feedback (
    feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id  BIGINT      NOT NULL REFERENCES chat_messages (message_id) ON DELETE CASCADE,
    user_id     BIGINT      REFERENCES users (user_id),
    guest_id    UUID        REFERENCES guests (guest_id),
    rating      VARCHAR(10) NOT NULL,               -- LIKE / DISLIKE
    reason_code VARCHAR(30),                        -- WRONG_INFO / NOT_RELATED / HARD_TO_READ
    comment     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- 부분 유니크 인덱스(아래)와 함께 JPA로는 표현이 안 되므로 서비스 레이어에서도 검증해야 한다.
    CONSTRAINT ck_feedback_actor CHECK (user_id IS NOT NULL OR guest_id IS NOT NULL)
);

CREATE TRIGGER trg_message_feedback_updated_at
    BEFORE UPDATE ON message_feedback
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- 메시지당 회원 1건 / 게스트 1건. NULL이 섞여 복합 UNIQUE가 안 되므로 부분 인덱스로 처리한다.
CREATE UNIQUE INDEX uk_feedback_user
    ON message_feedback (message_id, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX uk_feedback_guest
    ON message_feedback (message_id, guest_id) WHERE guest_id IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────
-- 매장
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE stores (
    store_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    phone       VARCHAR(20),
    address     VARCHAR(255)  NOT NULL,             -- 지도 실패 시 텍스트 대체
    region_code VARCHAR(20),                        -- 위치 권한 거부 시 지역 검색용
    latitude    NUMERIC(9, 6) NOT NULL,
    longitude   NUMERIC(9, 6) NOT NULL,
    status      VARCHAR(20)   NOT NULL DEFAULT 'OPEN', -- OPEN / CLOSED_DOWN
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_stores_updated_at
    BEFORE UPDATE ON stores
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE store_service_types (
    service_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(40) NOT NULL UNIQUE,    -- NEW_LINE / PORT_IN / NAME_CHANGE / USIM_REISSUE
    name            VARCHAR(50) NOT NULL
);

CREATE TABLE store_services (
    store_id        BIGINT NOT NULL REFERENCES stores (store_id) ON DELETE CASCADE,
    service_type_id BIGINT NOT NULL REFERENCES store_service_types (service_type_id),
    PRIMARY KEY (store_id, service_type_id)
);

CREATE TABLE store_hours (
    store_id    BIGINT   NOT NULL REFERENCES stores (store_id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL,                  -- 1(월) ~ 7(일)
    open_time   TIME,
    close_time  TIME,
    is_closed   BOOLEAN  NOT NULL DEFAULT false,
    PRIMARY KEY (store_id, day_of_week)
);

-- ─────────────────────────────────────────────────────────────────────
-- 인덱스
-- ─────────────────────────────────────────────────────────────────────
-- ERD "인덱스" 섹션의 10개 + 벡터 검색용 HNSW.
-- FK 컬럼 인덱스는 여기에 없다. PostgreSQL은 FK를 걸어도 자식 쪽 인덱스를 자동 생성하지
-- 않으므로, 필요한 것은 각 기능 담당자가 실제 쿼리를 보고 추가한다.
CREATE INDEX idx_session_user      ON chat_sessions (user_id, last_active_at DESC);
CREATE INDEX idx_session_guest     ON chat_sessions (guest_id);
CREATE INDEX idx_guest_expires     ON guests (expires_at) WHERE merged_user_id IS NULL;
CREATE INDEX idx_execution_session ON chat_executions (session_id, started_at DESC);
CREATE INDEX idx_request_pending   ON consult_requests (session_id, status);
CREATE INDEX idx_generation_exec   ON llm_generations (execution_id);
CREATE INDEX idx_source_message    ON message_sources (message_id);
CREATE INDEX idx_faq_category      ON faqs (category) WHERE status = 'ACTIVE';
CREATE INDEX idx_embed_sync        ON faq_embeddings (sync_status) WHERE sync_status <> 'SYNCED';
CREATE INDEX idx_store_service     ON store_services (service_type_id, store_id);

-- HNSW: ivfflat과 달리 인덱스 생성 시 리스트 개수 튜닝/재학습이 필요 없어 FAQ 규모(수천~수만 건)에는
-- 운영 부담이 적다. bge-m3 임베딩은 코사인 유사도 기준으로 비교하므로 vector_cosine_ops를 사용한다.
-- 이 인덱스가 없으면 유사도 검색이 전건 순차 스캔이 된다.
CREATE INDEX idx_faq_embeddings_embedding ON faq_embeddings
    USING hnsw (embedding vector_cosine_ops);
