-- 검색마다 질문+답변 벡터(Q_A)의 1위 후보 점수를 남긴다. 임계값 미달 후보는 검색 결과에서 잘려 다른 곳에 남지 않는다.
-- 후보가 없거나 Q_A를 조회하지 않은 검색은 qa_top_score가 NULL이다.
-- passed는 실제 검색 결과가 있었는지다. 이중 벡터에서는 질문 벡터만으로도 통과할 수 있어 점수만으로는 알 수 없다
CREATE TABLE faq_search_scores (
    search_score_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qa_top_score    DOUBLE PRECISION,
    passed          BOOLEAN     NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_faq_search_scores_created ON faq_search_scores (created_at);