CREATE TABLE chat_input_guard_states (
    guard_state_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    guest_id UUID REFERENCES guests(guest_id) ON DELETE CASCADE,
    counting_from_at TIMESTAMPTZ NOT NULL,
    restriction_started_at TIMESTAMPTZ,
    restriction_until TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_input_guard_actor CHECK (num_nonnulls(user_id, guest_id) = 1),
    CONSTRAINT ck_input_guard_restriction CHECK (
        (restriction_started_at IS NULL AND restriction_until IS NULL)
        OR (restriction_started_at IS NOT NULL AND restriction_until IS NOT NULL
            AND restriction_until > restriction_started_at)
    )
);

CREATE UNIQUE INDEX uk_input_guard_user ON chat_input_guard_states(user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX uk_input_guard_guest ON chat_input_guard_states(guest_id) WHERE guest_id IS NOT NULL;

CREATE TABLE chat_input_guard_events (
    guard_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guard_state_id BIGINT NOT NULL REFERENCES chat_input_guard_states(guard_state_id) ON DELETE CASCADE,
    detected_at TIMESTAMPTZ NOT NULL,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    guest_id UUID REFERENCES guests(guest_id) ON DELETE SET NULL,
    session_id BIGINT REFERENCES chat_sessions(session_id) ON DELETE SET NULL,
    message_id BIGINT REFERENCES chat_messages(message_id) ON DELETE SET NULL,
    request_id UUID,
    request_fingerprint VARCHAR(64),
    sanitized_content TEXT NOT NULL,
    detections JSONB NOT NULL,
    actions JSONB NOT NULL,
    counted_violation BOOLEAN NOT NULL,
    violation_count INTEGER NOT NULL CHECK (violation_count >= 0),
    restriction_started_at TIMESTAMPTZ,
    restriction_until TIMESTAMPTZ,
    policy_version VARCHAR(50) NOT NULL,
    response_snapshot JSONB NOT NULL,
    review_status VARCHAR(20) NOT NULL DEFAULT 'UNREVIEWED',
    reviewed_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    CONSTRAINT ck_input_guard_review CHECK (review_status IN ('UNREVIEWED','CONFIRMED','FALSE_POSITIVE')),
    CONSTRAINT ck_input_guard_request CHECK (num_nonnulls(request_id, request_fingerprint) IN (0,2))
);

CREATE UNIQUE INDEX uk_input_guard_request ON chat_input_guard_events(guard_state_id, request_id)
    WHERE request_id IS NOT NULL;
CREATE INDEX ix_input_guard_window ON chat_input_guard_events(guard_state_id, detected_at)
    WHERE counted_violation;
CREATE INDEX ix_input_guard_event_time ON chat_input_guard_events(detected_at DESC, guard_event_id DESC);

-- 오탐 표시는 검토 이력이다. 과거 조치·횟수 스냅샷이나 현재 제한을 변경하는 트리거는 두지 않는다.
-- chat_messages의 BLOCKED 타입은 VARCHAR 컬럼에서 사용하므로 기존 타입 컬럼은 변경하지 않는다.
