CREATE TABLE users (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    name          VARCHAR(50),
    phone         VARCHAR(20),
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    withdrawn_at  TIMESTAMPTZ,
    CONSTRAINT ck_user_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_user_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE TABLE guests (
    guest_id       UUID PRIMARY KEY,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at   TIMESTAMPTZ,
    expires_at     TIMESTAMPTZ NOT NULL,
    merged_user_id BIGINT REFERENCES users (user_id),
    merged_at      TIMESTAMPTZ
);

CREATE INDEX idx_guests_merged_user_id ON guests (merged_user_id);

CREATE TABLE social_accounts (
    social_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL REFERENCES users (user_id),
    provider          VARCHAR(20)  NOT NULL,
    provider_user_id  VARCHAR(100) NOT NULL,
    email             VARCHAR(255),
    connected_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_social_provider CHECK (provider IN ('KAKAO', 'GOOGLE')),
    CONSTRAINT uk_social_provider UNIQUE (provider, provider_user_id)
);

CREATE INDEX idx_social_accounts_user_id ON social_accounts (user_id);
