CREATE TABLE store_service_types (
    service_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(40) NOT NULL UNIQUE,
    name            VARCHAR(50) NOT NULL,
    CONSTRAINT ck_service_type_code CHECK (code IN ('NEW_LINE', 'PORT_IN', 'NAME_CHANGE', 'USIM_REISSUE'))
);

CREATE TABLE stores (
    store_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)   NOT NULL,
    phone       VARCHAR(20),
    address     VARCHAR(255)   NOT NULL,
    region_code VARCHAR(20),
    latitude    NUMERIC(9, 6)  NOT NULL,
    longitude   NUMERIC(9, 6)  NOT NULL,
    status      VARCHAR(20)    NOT NULL DEFAULT 'OPEN',
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT ck_store_status CHECK (status IN ('OPEN', 'CLOSED_DOWN'))
);

CREATE INDEX idx_stores_region_code ON stores (region_code);

CREATE TRIGGER trg_stores_updated_at
    BEFORE UPDATE ON stores
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE store_services (
    store_id        BIGINT NOT NULL REFERENCES stores (store_id),
    service_type_id BIGINT NOT NULL REFERENCES store_service_types (service_type_id),
    PRIMARY KEY (store_id, service_type_id)
);

CREATE TABLE store_hours (
    store_id    BIGINT   NOT NULL REFERENCES stores (store_id),
    day_of_week SMALLINT NOT NULL,
    open_time   TIME,
    close_time  TIME,
    is_closed   BOOLEAN  NOT NULL DEFAULT false,
    PRIMARY KEY (store_id, day_of_week),
    CONSTRAINT ck_store_hours_day CHECK (day_of_week BETWEEN 0 AND 6)
);
