CREATE TABLE faqs (
    faq_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category     VARCHAR(30) NOT NULL,
    question     TEXT        NOT NULL,
    answer       TEXT        NOT NULL,
    policy_ref   VARCHAR(50),
    version      INT         NOT NULL DEFAULT 1,
    content_hash VARCHAR(64),
    status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    -- member 도메인 참조. 도메인 결합을 피하려고 FK를 걸지 않고 id만 보관한다.
    created_by   BIGINT,
    updated_by   BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_faq_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED'))
);

CREATE INDEX idx_faqs_category ON faqs (category);

CREATE TRIGGER trg_faqs_updated_at
    BEFORE UPDATE ON faqs
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE faq_embeddings (
    faq_id      BIGINT      PRIMARY KEY REFERENCES faqs (faq_id) ON DELETE CASCADE,
    embedding   vector(1024) NOT NULL,
    model_name  VARCHAR(50) NOT NULL DEFAULT 'bge-m3',
    faq_version INT         NOT NULL,
    sync_status VARCHAR(20) NOT NULL DEFAULT 'SYNCED',
    embedded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_faq_embedding_sync_status CHECK (sync_status IN ('PENDING', 'SYNCED', 'FAILED'))
);

-- HNSW: ivfflat과 달리 인덱스 생성 시 리스트 개수 튜닝/재학습이 필요 없어 FAQ 규모(수천~수만 건)에는
-- 운영 부담이 적다. bge-m3 임베딩은 코사인 유사도 기준으로 비교하므로 vector_cosine_ops를 사용한다.
CREATE INDEX idx_faq_embeddings_embedding ON faq_embeddings
    USING hnsw (embedding vector_cosine_ops);
