CREATE TABLE chat_sessions (
    session_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- member 도메인 참조. 도메인 결합을 피하려고 FK를 걸지 않고 id만 보관한다.
    user_id        BIGINT,
    guest_id       UUID,
    title          VARCHAR(100),
    status         VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    summary        TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_active_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_session_status CHECK (status IN ('ACTIVE', 'NEED_CLARIFICATION', 'CLOSED')),
    CONSTRAINT ck_session_owner CHECK (user_id IS NOT NULL OR guest_id IS NOT NULL)
);

CREATE INDEX idx_chat_sessions_user_id ON chat_sessions (user_id);
CREATE INDEX idx_chat_sessions_guest_id ON chat_sessions (guest_id);

CREATE TABLE chat_messages (
    message_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    BIGINT      NOT NULL REFERENCES chat_sessions (session_id),
    sequence_no   INT         NOT NULL,
    reply_to_id   BIGINT      REFERENCES chat_messages (message_id),
    role          VARCHAR(20) NOT NULL,
    message_type  VARCHAR(30) NOT NULL,
    content       TEXT,
    status        VARCHAR(20),
    answer_basis  VARCHAR(20),
    follow_ups    JSONB,
    store_results JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at  TIMESTAMPTZ,
    CONSTRAINT uk_message_seq UNIQUE (session_id, sequence_no),
    CONSTRAINT ck_message_role CHECK (role IN ('USER', 'ASSISTANT')),
    CONSTRAINT ck_message_type CHECK (message_type IN ('QUESTION', 'ANSWER', 'CLARIFICATION', 'STORE_RESULT', 'ERROR')),
    CONSTRAINT ck_message_status CHECK (status IN ('GENERATING', 'COMPLETED', 'FAILED', 'TIMEOUT', 'CANCELLED')),
    CONSTRAINT ck_message_answer_basis CHECK (answer_basis IN ('GROUNDED', 'NO_EVIDENCE', 'OUT_OF_SCOPE'))
);

CREATE INDEX idx_chat_messages_reply_to_id ON chat_messages (reply_to_id);

CREATE TABLE consult_requests (
    consult_request_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         BIGINT      NOT NULL REFERENCES chat_sessions (session_id),
    origin_message_id  BIGINT      NOT NULL REFERENCES chat_messages (message_id),
    subquery_order      SMALLINT    NOT NULL,
    intent              VARCHAR(20) NOT NULL,
    query_text          TEXT        NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    version             INT         NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_consult_request_intent CHECK (intent IN ('FAQ', 'STORE')),
    CONSTRAINT ck_consult_request_status CHECK (status IN ('PENDING', 'WAITING_CONDITION', 'DONE', 'CANCELLED'))
);

CREATE INDEX idx_consult_requests_session_id ON consult_requests (session_id);
CREATE INDEX idx_consult_requests_origin_message_id ON consult_requests (origin_message_id);

CREATE TRIGGER trg_consult_requests_updated_at
    BEFORE UPDATE ON consult_requests
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE consult_conditions (
    condition_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consult_request_id   BIGINT      NOT NULL REFERENCES consult_requests (consult_request_id),
    condition_key        VARCHAR(50) NOT NULL,
    condition_value       VARCHAR(255),
    source                VARCHAR(20),
    status                VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    asked_message_id      BIGINT      REFERENCES chat_messages (message_id),
    answered_message_id   BIGINT      REFERENCES chat_messages (message_id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_condition_key UNIQUE (consult_request_id, condition_key),
    CONSTRAINT ck_condition_source CHECK (source IN ('EXTRACTED', 'ASKED')),
    CONSTRAINT ck_condition_status CHECK (status IN ('PENDING', 'FILLED', 'DECLINED'))
);

CREATE INDEX idx_consult_conditions_asked_message_id ON consult_conditions (asked_message_id);
CREATE INDEX idx_consult_conditions_answered_message_id ON consult_conditions (answered_message_id);

CREATE TRIGGER trg_consult_conditions_updated_at
    BEFORE UPDATE ON consult_conditions
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE query_routings (
    routing_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id             BIGINT      NOT NULL UNIQUE REFERENCES chat_messages (message_id),
    intent                 VARCHAR(20) NOT NULL,
    refined_query          TEXT,
    extracted_conditions   JSONB,
    confidence             NUMERIC(4, 3),
    method                 VARCHAR(20),
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_routing_intent CHECK (intent IN ('FAQ', 'STORE', 'BOTH', 'UNKNOWN')),
    CONSTRAINT ck_routing_method CHECK (method IN ('RULE', 'LLM'))
);

CREATE TABLE chat_executions (
    execution_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         BIGINT      NOT NULL REFERENCES chat_sessions (session_id),
    input_message_id   BIGINT      NOT NULL REFERENCES chat_messages (message_id),
    output_message_id  BIGINT      REFERENCES chat_messages (message_id),
    status             VARCHAR(20) NOT NULL,
    started_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at           TIMESTAMPTZ,
    error_code         VARCHAR(50),
    CONSTRAINT ck_execution_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);

CREATE INDEX idx_chat_executions_session_id ON chat_executions (session_id);
CREATE INDEX idx_chat_executions_input_message_id ON chat_executions (input_message_id);
CREATE INDEX idx_chat_executions_output_message_id ON chat_executions (output_message_id);

CREATE TABLE llm_generations (
    generation_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id     BIGINT      NOT NULL REFERENCES chat_executions (execution_id),
    task_type        VARCHAR(30) NOT NULL,
    attempt          SMALLINT    NOT NULL DEFAULT 1,
    model            VARCHAR(50),
    prompt_version   VARCHAR(30),
    context_count    INT,
    first_token_ms   INT,
    total_ms         INT,
    status           VARCHAR(30) NOT NULL,
    error_message    TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_generation_task_type CHECK (task_type IN ('ROUTING', 'RAG_ANSWER', 'CLARIFICATION', 'FOLLOW_UP', 'SUMMARY')),
    CONSTRAINT ck_generation_status CHECK (status IN ('SUCCESS', 'NO_EVIDENCE', 'TIMEOUT', 'CONNECTION_FAILED', 'MODEL_ERROR', 'CANCELLED'))
);

CREATE INDEX idx_llm_generations_execution_id ON llm_generations (execution_id);

CREATE TABLE message_feedback (
    feedback_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id   BIGINT      NOT NULL REFERENCES chat_messages (message_id),
    -- member 도메인 참조. 도메인 결합을 피하려고 FK를 걸지 않고 id만 보관한다.
    user_id      BIGINT,
    guest_id     UUID,
    rating       VARCHAR(10) NOT NULL,
    reason_code  VARCHAR(30),
    comment      TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_feedback_rating CHECK (rating IN ('LIKE', 'DISLIKE')),
    CONSTRAINT ck_feedback_reason_code CHECK (reason_code IN ('WRONG_INFO', 'NOT_RELATED', 'HARD_TO_READ')),
    CONSTRAINT ck_feedback_actor CHECK (user_id IS NOT NULL OR guest_id IS NOT NULL)
);

CREATE INDEX idx_message_feedback_message_id ON message_feedback (message_id);
-- 메시지당 회원 1건 / 게스트 1건으로 피드백을 제한한다 (부분 유니크 인덱스: 값이 NULL인 행은 대상에서 제외).
CREATE UNIQUE INDEX uk_feedback_user ON message_feedback (message_id, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX uk_feedback_guest ON message_feedback (message_id, guest_id) WHERE guest_id IS NOT NULL;

CREATE TRIGGER trg_message_feedback_updated_at
    BEFORE UPDATE ON message_feedback
    FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE message_sources (
    source_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id     BIGINT   NOT NULL REFERENCES chat_messages (message_id),
    -- faq 도메인 참조. 답변 당시 스냅샷이라 FK보다 값 복사가 맞고, 도메인도 달라 id만 보관한다.
    faq_id         BIGINT,
    title_snapshot VARCHAR(200),
    faq_version    INT,
    faq_updated_at DATE,
    search_rank    SMALLINT,
    score          NUMERIC(5, 4)
);

CREATE INDEX idx_message_sources_message_id ON message_sources (message_id);
CREATE INDEX idx_message_sources_faq_id ON message_sources (faq_id);
